#include "unity/unity.h"

/* Declare test functions */
void test_pmm_init_alloc_free_count(void);
void test_pmm_reserve_range(void);
void test_kheap_basic_alloc_free(void);
void test_vmm_map_translate_unmap_page(void);
void test_vmm_map_range_and_unmap_range(void);
void test_vmm_user_exec_mapping_flags(void);
void test_vmm_kernel_mapping_can_be_replaced_with_user_mapping(void);
void test_process_user_range_contains_registered_regions(void);
void test_process_remove_user_region_exact_match(void);
void test_process_user_region_mapping_metadata_round_trips(void);
void test_process_alloc_user_region_bumps_page_aligned_arena(void);
void test_process_alloc_user_region_respects_region_limit(void);
void test_process_current_and_region_limits(void);
void test_process_entry_page_table_and_exit_state(void);
void test_process_save_context_copies_registers_and_trap_state(void);
void test_process_load_context_writes_exception_frame(void);
void test_process_table_alloc_release_and_limits(void);
void test_process_at_returns_active_slots_only(void);
void test_process_wait_zombie_returns_exit_and_releases_slot(void);
void test_process_kill_marks_target_zombie(void);
void test_process_next_runnable_round_robin_and_reclaim_zombies(void);
void test_boot_program_find_existing_program(void);
void test_boot_program_find_rejects_missing_and_invalid_names(void);
void test_boot_program_metadata_round_trips_image_range(void);
void test_boot_program_find_returns_each_registered_app(void);
void test_boot_program_find_resolves_editor_and_panel(void);
void test_boot_program_find_resolves_remaining_registered_apps(void);
void test_boot_program_image_points_to_flat_header_magic(void);
void test_boot_program_editor_image_size_matches_assembly_blob(void);
void test_boot_program_kos_hello_uses_kos_magic(void);
void test_bootfs_find_existing_file_metadata(void);
void test_bootfs_find_returns_each_registered_app(void);
void test_bootfs_find_rejects_missing_and_invalid_names(void);
void test_bootfs_finds_editor_and_panel_for_taskbar_spawn(void);
void test_bootfs_finds_monitor_win_and_clock(void);
void test_bootfs_read_copies_requested_range(void);
void test_bootfs_read_clamps_at_end_of_file(void);
void test_bootfs_read_rejects_invalid_inputs(void);
void test_bootfs_mount_vfs_exposes_kolibri_paths(void);
void test_bootfs_mount_vfs_exposes_editor_and_panel_paths(void);
void test_bootfs_mount_vfs_exposes_remaining_app_paths(void);
void test_bootfs_mount_vfs_reads_app_through_vfs(void);
void test_bootfs_mount_vfs_reads_editor_through_vfs(void);
void test_bootfs_old_user_demo_path_is_gone(void);
void test_user_image_entry_uses_base_plus_offset(void);
void test_user_image_prepare_process_registers_image_and_stack(void);
void test_user_image_load_copy_copies_source_and_sets_descriptor(void);
void test_user_image_load_flat_uses_header_entry_table(void);
void test_user_image_load_bootfs_flat_uses_named_boot_file(void);
void test_user_image_prepare_process_rejects_invalid_inputs(void);
void test_user_image_load_copy_rejects_invalid_ranges(void);
void test_user_image_load_flat_rejects_invalid_headers(void);
void test_user_image_load_flat_accepts_kos_header(void);
void test_user_image_load_flat_kos_rejects_bad_inputs(void);
void test_user_image_load_bootfs_flat_rejects_missing_file(void);
void test_user_vm_map_anonymous_installs_user_pte(void);
void test_user_vm_unmap_anonymous_removes_pte_and_frees_pages(void);
void test_user_vm_rejects_invalid_inputs_without_regions(void);
void test_user_vm_map_physical_maps_registered_region(void);
void test_user_vm_map_physical_rejects_unregistered_region(void);
void test_user_vm_physical_mappings_stay_per_process(void);
void test_vfs_mount_and_find_static_node(void);
void test_vfs_read_dispatches_to_node_reader(void);
void test_vfs_rejects_invalid_mounts_and_reads(void);
void test_vfs_mount_static_respects_node_limit(void);
void test_vfs_open_read_fd_and_close(void);
void test_vfs_open_flags_enforce_read_write_modes(void);
void test_vfs_open_rejects_missing_and_invalid_descriptors(void);
void test_vfs_open_respects_descriptor_limit_and_reuses_closed_slot(void);
void test_vfs_stat_reports_node_size(void);
void test_vfs_list_root_returns_mounted_paths(void);
void test_vfs_list_truncates_to_capacity(void);
void test_vfs_seek_sets_descriptor_offset(void);
void test_vfs_write_dispatches_to_node_writer(void);
void test_vfs_open_write_fd_updates_offset_and_size(void);
void test_vfs_unlink_rejects_non_fat_paths(void);
void test_vfs_rename_rejects_non_fat_paths(void);
void test_tmpfs_create_write_read_stat_and_delete(void);
void test_tmpfs_write_clamps_to_file_capacity(void);
void test_tmpfs_rejects_invalid_inputs_and_duplicates(void);
void test_tmpfs_respects_file_limit_and_reuses_deleted_slot(void);
void test_tmpfs_mount_vfs_read_write_and_stat(void);
void test_tmpfs_mount_vfs_rejects_missing_and_invalid_inputs(void);
void test_fat32_mount_reads_geometry(void);
void test_fat32_open_root_finds_8_3_file(void);
void test_fat32_read_file_across_cluster_chain(void);
void test_fat32_read_clamps_and_honors_offset(void);
void test_fat32_rejects_invalid_boot_sector_and_missing_files(void);
void test_fat32_mount_vfs_file_reads_through_vfs(void);
void test_fat32_list_root_returns_short_names(void);
void test_fat32_mount_vfs_root_lists_through_vfs(void);
void test_fat32_write_overwrites_and_updates_size(void);
void test_fat32_write_grows_within_chain_and_rejects_capacity_overflow(void);
void test_fat32_mount_vfs_file_writes_through_vfs(void);
void test_fat32_create_writes_dir_entry_and_allocates_cluster(void);
void test_fat32_create_then_write_persists_through_open(void);
void test_fat32_create_rejects_duplicate_name(void);
void test_fat32_write_grows_chain_when_capacity_exhausted(void);
void test_fat32_delete_frees_chain_and_removes_entry(void);
void test_fat32_rename_updates_short_name_in_place(void);
void test_fat32_rename_rejects_destination_collision(void);
void test_fat32_write_to_brand_new_file_uses_allocated_cluster(void);
void test_ipc_send_and_recv_message(void);
void test_ipc_keeps_messages_by_target_pid(void);
void test_ipc_rejects_invalid_inputs_and_full_queue(void);
void test_font_draw_char_renders_8x8_glyph(void);
void test_font_draw_text_advances_and_handles_lowercase(void);
void test_font_draw_text_renders_punctuation(void);
void test_font_draw_text_clips_at_framebuffer_edge(void);
void test_font_draw_text_handles_newline(void);
void test_font_draw_text_clipped_stops_at_max_h(void);
void test_font_draw_text_clipped_handles_zero_max_h(void);
void test_gui_init_for_framebuffer_starts_with_empty_desktop(void);
void test_gui_create_draws_windows_in_creation_order(void);
void test_gui_move_window_redraws_at_new_position(void);
void test_gui_rejects_invalid_inputs_and_window_limit(void);
void test_gui_delivers_key_to_focused_window(void);
void test_gui_cursor_move_clamps_to_bounds(void);
void test_gui_draw_renders_16x16_cursor_over_desktop(void);
void test_gui_left_click_raises_window_under_cursor(void);
void test_gui_left_click_on_background_clears_focus(void);
void test_gui_right_and_middle_buttons_set_mask_without_focus_change(void);
void test_gui_focused_window_gets_brighter_border(void);
void test_gui_drag_moves_window_following_cursor(void);
void test_gui_drag_rejects_unknown_window(void);
void test_gui_drag_stays_active_until_left_release(void);
void test_gui_title_bar_shifts_owner_draw_below_bar(void);
void test_gui_title_bar_paints_bar_and_text(void);
void test_gui_cursor_shape_changes_over_clickable_title_decoration(void);
void test_gui_set_cursor_shape_rejects_unknown_shapes(void);
void test_gui_set_title_bar_rejects_height_larger_than_window(void);
void test_gui_set_title_bar_zero_disables_bar(void);
void test_gui_close_button_pushed_event_on_title_bar_click(void);
void test_gui_close_button_destroys_window_for_dead_owner(void);
void test_gui_close_button_destroys_window_for_reclaimed_owner(void);
void test_gui_close_button_click_outside_box_starts_drag(void);
void test_gui_focus_window_switches_to_target(void);
void test_gui_focus_window_raises_target_above_overlap(void);
void test_gui_window_for_pid_returns_owner_windows(void);
void test_gui_backing_buffer_lazy_allocates_on_first_draw(void);
void test_gui_backing_buffer_init_to_bg_color(void);
void test_gui_backing_buffer_survives_compositor_redraw(void);
void test_gui_backing_buffer_follows_window_on_drag(void);
void test_gui_backing_buffer_freed_on_destroy(void);
void test_gui_backing_buffer_reallocates_when_window_reused(void);
void test_gui_damage_init_queues_full_sentinel(void);
void test_gui_damage_add_clips_to_framebuffer(void);
void test_gui_damage_add_merges_overlapping_rects(void);
void test_gui_damage_add_full_collapses_to_sentinel(void);
void test_gui_damage_overflow_collapses_to_sentinel(void);
void test_gui_damage_draw_text_pushes_tight_rect(void);
void test_gui_damage_draw_rect_pushes_content_rect(void);
void test_gui_damage_title_bar_offset_in_draw_text(void);
void test_gui_damage_move_pushes_union_rect(void);
void test_gui_damage_partial_repaint_leaves_pixels_outside_rect(void);
void test_gui_damage_full_sentinel_re_paints_everything(void);
void test_input_injects_ascii_byte_directly(void);
void test_input_translates_esc_up_to_key_up(void);
void test_input_translates_esc_down_to_key_down(void);
void test_input_translates_esc_left_and_right(void);
void test_input_keeps_esc_for_unrelated_followup(void);
void test_input_supports_consecutive_esc_sequences(void);
void test_input_poll_char_mask_strips_high_bits(void);
void test_input_peek_returns_event_without_removing(void);
void test_input_peek_returns_minus_one_when_empty(void);
void test_input_peek_then_poll_returns_same_event(void);
void test_hid_parse_boot_keyboard_decodes_modifiers_and_keys(void);
void test_hid_parse_boot_keyboard_rejects_short_buffer(void);
void test_hid_parse_boot_keyboard_rejects_null(void);
void test_hid_parse_boot_mouse_decodes_buttons_and_motion(void);
void test_hid_parse_boot_mouse_sign_extends_negative_motion(void);
void test_hid_parse_boot_mouse_rejects_short_buffer(void);
void test_hid_usage_to_ascii_lowercase_letters(void);
void test_hid_usage_to_ascii_uppercase_letters_with_shift(void);
void test_hid_usage_to_ascii_digits_and_punctuation(void);
void test_hid_usage_to_ascii_shifted_punctuation(void);
void test_hid_usage_to_ascii_returns_zero_for_modifiers(void);
void test_hid_usage_to_ascii_returns_zero_for_function_keys(void);
void test_hid_usage_to_ascii_high_usage_ids_return_zero(void);
void test_hid_keyboard_report_emits_press_for_new_key(void);
void test_hid_keyboard_report_emits_release_when_key_dropped(void);
void test_hid_keyboard_report_handles_two_key_rollover(void);
void test_hid_mouse_report_emits_move_when_deltas_nonzero(void);
void test_hid_mouse_report_emits_button_press_and_release(void);
void test_hid_mouse_report_emits_no_events_when_idle(void);
void test_hid_mouse_report_rejects_null_arguments(void);
void test_pci_bar_address_extracts_32bit_mmio(void);
void test_pci_bar_address_ignores_io_space_bar(void);
void test_pci_bar_address_combines_64bit_pair(void);
void test_pci_bar_address_low_32bit_ignores_next_bar(void);
void test_usb_walk_configuration_finds_interface(void);
void test_usb_walk_configuration_attaches_endpoint(void);
void test_usb_walk_configuration_attaches_hid_class_descriptor(void);
void test_usb_walk_configuration_rejects_short_buffer(void);
void test_usb_walk_configuration_rejects_wrong_descriptor_type(void);
void test_usb_find_interface_returns_null_when_no_match(void);
void test_usb_find_interface_matches_exact_class_subclass_protocol(void);
void test_usb_find_endpoint_in_returns_interrupt_endpoint(void);
void test_usb_find_endpoint_in_returns_null_when_too_small(void);
void test_pci_assign_bars_skips_already_programmed_bars(void);
void test_pci_assign_bars_function_pointer_exists(void);
void test_hid_state_reset_clears_count(void);
void test_hid_state_reset_clears_device_endpoints(void);
void test_hid_poll_all_returns_zero_on_empty_state(void);
void test_hid_state_count_field_is_accessible(void);
void test_hid_max_devices_constant_is_sane(void);
void test_hid_init_registers_mouse_protocol(void);
void test_hid_init_zeroes_prev_keys_for_new_device(void);
void test_hid_init_returns_zero_when_no_boot_interfaces(void);
void test_hid_init_returns_zero_for_null_state(void);
void test_hid_init_keeps_max_four_devices(void);
void test_gui_draw_fills_vertical_gradient(void);
void test_fb_init_rejects_invalid_geometry(void);
void test_fb_putpixel_and_fillrect_clip_to_bounds(void);
void test_fb_blit_copies_and_clips_source_pixels(void);
void test_fb_draw_line_rect_circle_and_alpha(void);
void test_dtb_get_framebuffer_reads_simple_framebuffer(void);
void test_dtb_get_framebuffer_rejects_incomplete_node(void);
void test_virtio_blk_probe_reads_capacity(void);
void test_virtio_blk_probe_rejects_non_block_device(void);
void test_virtio_blk_probe_range_finds_later_transport(void);
void test_virtio_blk_init_programs_modern_queue(void);

int main(void) {
    UNITY_BEGIN();

    RUN_TEST(test_pmm_init_alloc_free_count);
    RUN_TEST(test_pmm_reserve_range);
    RUN_TEST(test_kheap_basic_alloc_free);
    RUN_TEST(test_vmm_map_translate_unmap_page);
    RUN_TEST(test_vmm_map_range_and_unmap_range);
    RUN_TEST(test_vmm_user_exec_mapping_flags);
    RUN_TEST(test_vmm_kernel_mapping_can_be_replaced_with_user_mapping);
    RUN_TEST(test_process_user_range_contains_registered_regions);
    RUN_TEST(test_process_remove_user_region_exact_match);
    RUN_TEST(test_process_user_region_mapping_metadata_round_trips);
    RUN_TEST(test_process_alloc_user_region_bumps_page_aligned_arena);
    RUN_TEST(test_process_alloc_user_region_respects_region_limit);
    RUN_TEST(test_process_current_and_region_limits);
    RUN_TEST(test_process_entry_page_table_and_exit_state);
    RUN_TEST(test_process_save_context_copies_registers_and_trap_state);
    RUN_TEST(test_process_load_context_writes_exception_frame);
    RUN_TEST(test_process_table_alloc_release_and_limits);
    RUN_TEST(test_process_at_returns_active_slots_only);
    RUN_TEST(test_process_wait_zombie_returns_exit_and_releases_slot);
    RUN_TEST(test_process_kill_marks_target_zombie);
    RUN_TEST(test_process_next_runnable_round_robin_and_reclaim_zombies);
    RUN_TEST(test_boot_program_find_existing_program);
    RUN_TEST(test_boot_program_find_rejects_missing_and_invalid_names);
    RUN_TEST(test_boot_program_metadata_round_trips_image_range);
    RUN_TEST(test_boot_program_find_returns_each_registered_app);
    RUN_TEST(test_boot_program_find_resolves_editor_and_panel);
    RUN_TEST(test_boot_program_find_resolves_remaining_registered_apps);
    RUN_TEST(test_boot_program_image_points_to_flat_header_magic);
    RUN_TEST(test_boot_program_editor_image_size_matches_assembly_blob);
    RUN_TEST(test_boot_program_kos_hello_uses_kos_magic);
    RUN_TEST(test_bootfs_find_existing_file_metadata);
    RUN_TEST(test_bootfs_find_returns_each_registered_app);
    RUN_TEST(test_bootfs_find_rejects_missing_and_invalid_names);
    RUN_TEST(test_bootfs_finds_editor_and_panel_for_taskbar_spawn);
    RUN_TEST(test_bootfs_finds_monitor_win_and_clock);
    RUN_TEST(test_bootfs_read_copies_requested_range);
    RUN_TEST(test_bootfs_read_clamps_at_end_of_file);
    RUN_TEST(test_bootfs_read_rejects_invalid_inputs);
    RUN_TEST(test_bootfs_mount_vfs_exposes_kolibri_paths);
    RUN_TEST(test_bootfs_mount_vfs_exposes_editor_and_panel_paths);
    RUN_TEST(test_bootfs_mount_vfs_exposes_remaining_app_paths);
    RUN_TEST(test_bootfs_mount_vfs_reads_app_through_vfs);
    RUN_TEST(test_bootfs_mount_vfs_reads_editor_through_vfs);
    RUN_TEST(test_bootfs_old_user_demo_path_is_gone);
    RUN_TEST(test_user_image_entry_uses_base_plus_offset);
    RUN_TEST(test_user_image_prepare_process_registers_image_and_stack);
    RUN_TEST(test_user_image_load_copy_copies_source_and_sets_descriptor);
    RUN_TEST(test_user_image_load_flat_uses_header_entry_table);
    RUN_TEST(test_user_image_load_bootfs_flat_uses_named_boot_file);
    RUN_TEST(test_user_image_prepare_process_rejects_invalid_inputs);
    RUN_TEST(test_user_image_load_copy_rejects_invalid_ranges);
    RUN_TEST(test_user_image_load_flat_rejects_invalid_headers);
    RUN_TEST(test_user_image_load_flat_accepts_kos_header);
    RUN_TEST(test_user_image_load_flat_kos_rejects_bad_inputs);
    RUN_TEST(test_user_image_load_bootfs_flat_rejects_missing_file);
    RUN_TEST(test_user_vm_map_anonymous_installs_user_pte);
    RUN_TEST(test_user_vm_unmap_anonymous_removes_pte_and_frees_pages);
    RUN_TEST(test_user_vm_rejects_invalid_inputs_without_regions);
    RUN_TEST(test_user_vm_map_physical_maps_registered_region);
    RUN_TEST(test_user_vm_map_physical_rejects_unregistered_region);
    RUN_TEST(test_user_vm_physical_mappings_stay_per_process);
    RUN_TEST(test_vfs_mount_and_find_static_node);
    RUN_TEST(test_vfs_read_dispatches_to_node_reader);
    RUN_TEST(test_vfs_rejects_invalid_mounts_and_reads);
    RUN_TEST(test_vfs_mount_static_respects_node_limit);
    RUN_TEST(test_vfs_open_read_fd_and_close);
    RUN_TEST(test_vfs_open_flags_enforce_read_write_modes);
    RUN_TEST(test_vfs_open_rejects_missing_and_invalid_descriptors);
    RUN_TEST(test_vfs_open_respects_descriptor_limit_and_reuses_closed_slot);
    RUN_TEST(test_vfs_stat_reports_node_size);
    RUN_TEST(test_vfs_list_root_returns_mounted_paths);
    RUN_TEST(test_vfs_list_truncates_to_capacity);
    RUN_TEST(test_vfs_seek_sets_descriptor_offset);
    RUN_TEST(test_vfs_write_dispatches_to_node_writer);
    RUN_TEST(test_vfs_open_write_fd_updates_offset_and_size);
    RUN_TEST(test_vfs_unlink_rejects_non_fat_paths);
    RUN_TEST(test_vfs_rename_rejects_non_fat_paths);
    RUN_TEST(test_tmpfs_create_write_read_stat_and_delete);
    RUN_TEST(test_tmpfs_write_clamps_to_file_capacity);
    RUN_TEST(test_tmpfs_rejects_invalid_inputs_and_duplicates);
    RUN_TEST(test_tmpfs_respects_file_limit_and_reuses_deleted_slot);
    RUN_TEST(test_tmpfs_mount_vfs_read_write_and_stat);
    RUN_TEST(test_tmpfs_mount_vfs_rejects_missing_and_invalid_inputs);
    RUN_TEST(test_fat32_mount_reads_geometry);
    RUN_TEST(test_fat32_open_root_finds_8_3_file);
    RUN_TEST(test_fat32_read_file_across_cluster_chain);
    RUN_TEST(test_fat32_read_clamps_and_honors_offset);
    RUN_TEST(test_fat32_rejects_invalid_boot_sector_and_missing_files);
    RUN_TEST(test_fat32_mount_vfs_file_reads_through_vfs);
    RUN_TEST(test_fat32_list_root_returns_short_names);
    RUN_TEST(test_fat32_mount_vfs_root_lists_through_vfs);
    RUN_TEST(test_fat32_write_overwrites_and_updates_size);
    RUN_TEST(test_fat32_write_grows_within_chain_and_rejects_capacity_overflow);
    RUN_TEST(test_fat32_mount_vfs_file_writes_through_vfs);
    RUN_TEST(test_fat32_create_writes_dir_entry_and_allocates_cluster);
    RUN_TEST(test_fat32_create_then_write_persists_through_open);
    RUN_TEST(test_fat32_create_rejects_duplicate_name);
    RUN_TEST(test_fat32_write_grows_chain_when_capacity_exhausted);
    RUN_TEST(test_fat32_delete_frees_chain_and_removes_entry);
    RUN_TEST(test_fat32_rename_updates_short_name_in_place);
    RUN_TEST(test_fat32_rename_rejects_destination_collision);
    RUN_TEST(test_fat32_write_to_brand_new_file_uses_allocated_cluster);
    RUN_TEST(test_ipc_send_and_recv_message);
    RUN_TEST(test_ipc_keeps_messages_by_target_pid);
    RUN_TEST(test_ipc_rejects_invalid_inputs_and_full_queue);
    RUN_TEST(test_font_draw_char_renders_8x8_glyph);
    RUN_TEST(test_font_draw_text_advances_and_handles_lowercase);
    RUN_TEST(test_font_draw_text_renders_punctuation);
    RUN_TEST(test_font_draw_text_clips_at_framebuffer_edge);
    RUN_TEST(test_font_draw_text_handles_newline);
    RUN_TEST(test_font_draw_text_clipped_stops_at_max_h);
    RUN_TEST(test_font_draw_text_clipped_handles_zero_max_h);
    RUN_TEST(test_gui_init_for_framebuffer_starts_with_empty_desktop);
    RUN_TEST(test_gui_create_draws_windows_in_creation_order);
    RUN_TEST(test_gui_move_window_redraws_at_new_position);
    RUN_TEST(test_gui_rejects_invalid_inputs_and_window_limit);
    RUN_TEST(test_gui_delivers_key_to_focused_window);
    RUN_TEST(test_gui_cursor_move_clamps_to_bounds);
    RUN_TEST(test_gui_draw_renders_16x16_cursor_over_desktop);
    RUN_TEST(test_gui_left_click_raises_window_under_cursor);
    RUN_TEST(test_gui_left_click_on_background_clears_focus);
    RUN_TEST(test_gui_right_and_middle_buttons_set_mask_without_focus_change);
    RUN_TEST(test_gui_focused_window_gets_brighter_border);
    RUN_TEST(test_gui_drag_moves_window_following_cursor);
    RUN_TEST(test_gui_drag_rejects_unknown_window);
    RUN_TEST(test_gui_draw_fills_vertical_gradient);
    RUN_TEST(test_gui_drag_stays_active_until_left_release);
    RUN_TEST(test_gui_title_bar_shifts_owner_draw_below_bar);
    RUN_TEST(test_gui_title_bar_paints_bar_and_text);
    RUN_TEST(test_gui_cursor_shape_changes_over_clickable_title_decoration);
    RUN_TEST(test_gui_set_cursor_shape_rejects_unknown_shapes);
    RUN_TEST(test_gui_set_title_bar_rejects_height_larger_than_window);
    RUN_TEST(test_gui_set_title_bar_zero_disables_bar);
    RUN_TEST(test_gui_close_button_pushed_event_on_title_bar_click);
    RUN_TEST(test_gui_close_button_destroys_window_for_dead_owner);
    RUN_TEST(test_gui_close_button_destroys_window_for_reclaimed_owner);
    RUN_TEST(test_gui_close_button_click_outside_box_starts_drag);
    RUN_TEST(test_gui_focus_window_switches_to_target);
    RUN_TEST(test_gui_focus_window_raises_target_above_overlap);
    RUN_TEST(test_gui_window_for_pid_returns_owner_windows);
    RUN_TEST(test_gui_backing_buffer_lazy_allocates_on_first_draw);
    RUN_TEST(test_gui_backing_buffer_init_to_bg_color);
    RUN_TEST(test_gui_backing_buffer_survives_compositor_redraw);
    RUN_TEST(test_gui_backing_buffer_follows_window_on_drag);
    RUN_TEST(test_gui_backing_buffer_freed_on_destroy);
    RUN_TEST(test_gui_backing_buffer_reallocates_when_window_reused);
    RUN_TEST(test_gui_damage_init_queues_full_sentinel);
    RUN_TEST(test_gui_damage_add_clips_to_framebuffer);
    RUN_TEST(test_gui_damage_add_merges_overlapping_rects);
    RUN_TEST(test_gui_damage_add_full_collapses_to_sentinel);
    RUN_TEST(test_gui_damage_overflow_collapses_to_sentinel);
    RUN_TEST(test_gui_damage_draw_text_pushes_tight_rect);
    RUN_TEST(test_gui_damage_draw_rect_pushes_content_rect);
    RUN_TEST(test_gui_damage_title_bar_offset_in_draw_text);
    RUN_TEST(test_gui_damage_move_pushes_union_rect);
    RUN_TEST(test_gui_damage_partial_repaint_leaves_pixels_outside_rect);
    RUN_TEST(test_gui_damage_full_sentinel_re_paints_everything);
    RUN_TEST(test_input_injects_ascii_byte_directly);
    RUN_TEST(test_input_translates_esc_up_to_key_up);
    RUN_TEST(test_input_translates_esc_down_to_key_down);
    RUN_TEST(test_input_translates_esc_left_and_right);
    RUN_TEST(test_input_keeps_esc_for_unrelated_followup);
    RUN_TEST(test_input_supports_consecutive_esc_sequences);
    RUN_TEST(test_input_poll_char_mask_strips_high_bits);
    RUN_TEST(test_input_peek_returns_event_without_removing);
    RUN_TEST(test_input_peek_returns_minus_one_when_empty);
    RUN_TEST(test_input_peek_then_poll_returns_same_event);
    RUN_TEST(test_hid_parse_boot_keyboard_decodes_modifiers_and_keys);
    RUN_TEST(test_hid_parse_boot_keyboard_rejects_short_buffer);
    RUN_TEST(test_hid_parse_boot_keyboard_rejects_null);
    RUN_TEST(test_hid_parse_boot_mouse_decodes_buttons_and_motion);
    RUN_TEST(test_hid_parse_boot_mouse_sign_extends_negative_motion);
    RUN_TEST(test_hid_parse_boot_mouse_rejects_short_buffer);
    RUN_TEST(test_hid_usage_to_ascii_lowercase_letters);
    RUN_TEST(test_hid_usage_to_ascii_uppercase_letters_with_shift);
    RUN_TEST(test_hid_usage_to_ascii_digits_and_punctuation);
    RUN_TEST(test_hid_usage_to_ascii_shifted_punctuation);
    RUN_TEST(test_hid_usage_to_ascii_returns_zero_for_modifiers);
    RUN_TEST(test_hid_usage_to_ascii_returns_zero_for_function_keys);
    RUN_TEST(test_hid_usage_to_ascii_high_usage_ids_return_zero);
    RUN_TEST(test_hid_keyboard_report_emits_press_for_new_key);
    RUN_TEST(test_hid_keyboard_report_emits_release_when_key_dropped);
    RUN_TEST(test_hid_keyboard_report_handles_two_key_rollover);
    RUN_TEST(test_hid_mouse_report_emits_move_when_deltas_nonzero);
    RUN_TEST(test_hid_mouse_report_emits_button_press_and_release);
    RUN_TEST(test_hid_mouse_report_emits_no_events_when_idle);
    RUN_TEST(test_hid_mouse_report_rejects_null_arguments);
    RUN_TEST(test_pci_bar_address_extracts_32bit_mmio);
    RUN_TEST(test_pci_bar_address_ignores_io_space_bar);
    RUN_TEST(test_pci_bar_address_combines_64bit_pair);
    RUN_TEST(test_pci_bar_address_low_32bit_ignores_next_bar);
    RUN_TEST(test_usb_walk_configuration_finds_interface);
    RUN_TEST(test_usb_walk_configuration_attaches_endpoint);
    RUN_TEST(test_usb_walk_configuration_attaches_hid_class_descriptor);
    RUN_TEST(test_usb_walk_configuration_rejects_short_buffer);
    RUN_TEST(test_usb_walk_configuration_rejects_wrong_descriptor_type);
    RUN_TEST(test_usb_find_interface_returns_null_when_no_match);
    RUN_TEST(test_usb_find_interface_matches_exact_class_subclass_protocol);
    RUN_TEST(test_usb_find_endpoint_in_returns_interrupt_endpoint);
    RUN_TEST(test_usb_find_endpoint_in_returns_null_when_too_small);
    RUN_TEST(test_pci_assign_bars_skips_already_programmed_bars);
    RUN_TEST(test_pci_assign_bars_function_pointer_exists);
    RUN_TEST(test_hid_state_reset_clears_count);
    RUN_TEST(test_hid_state_reset_clears_device_endpoints);
    RUN_TEST(test_hid_poll_all_returns_zero_on_empty_state);
    RUN_TEST(test_hid_state_count_field_is_accessible);
    RUN_TEST(test_hid_max_devices_constant_is_sane);
    RUN_TEST(test_hid_init_registers_mouse_protocol);
    RUN_TEST(test_hid_init_zeroes_prev_keys_for_new_device);
    RUN_TEST(test_hid_init_returns_zero_when_no_boot_interfaces);
    RUN_TEST(test_hid_init_returns_zero_for_null_state);
    RUN_TEST(test_hid_init_keeps_max_four_devices);
    RUN_TEST(test_fb_init_rejects_invalid_geometry);
    RUN_TEST(test_fb_putpixel_and_fillrect_clip_to_bounds);
    RUN_TEST(test_fb_blit_copies_and_clips_source_pixels);
    RUN_TEST(test_fb_draw_line_rect_circle_and_alpha);
    RUN_TEST(test_dtb_get_framebuffer_reads_simple_framebuffer);
    RUN_TEST(test_dtb_get_framebuffer_rejects_incomplete_node);
    RUN_TEST(test_virtio_blk_probe_reads_capacity);
    RUN_TEST(test_virtio_blk_probe_rejects_non_block_device);
    RUN_TEST(test_virtio_blk_probe_range_finds_later_transport);
    RUN_TEST(test_virtio_blk_init_programs_modern_queue);

    return UNITY_END();
}
